### ISSUE TITLE
Integrate daily Energy consumption

### ISSUE THREAD

**Issue by patricknitsch** [robbinjanssen/home-assistant-ojmicroline-thermostat#235]
It would be nice, if the daily Energy consumption would be available in the integration

At the moment I use a restful polling to get the daily values. This works semi optimal, because it works for a time and then it will not be updated. Then i have to restart HA.

Therefore i use the following code:

ViewType 2 is for the last seven days. To get the value from today, i use the date from tomorrow, because it will only shows the last seven days.

```
  - platform: rest
    name: Heizung Bad Energie heute
    method: POST
    headers:
      Content-Type: application/json
    resource_template: https://owd5-sl003-app.ojelectronics.com/api/EnergyUsage/GetEnergyUsage?sessionid={{ states('sensor.heizung_bad_token') }}
    payload_template: >
        {% set Date = (as_timestamp(now())+ (86400)) | timestamp_custom("%Y-%m-%d",true) %}
        {% set payload = {"APIKEY": "f219aab4-9ac0-4343-8422-b72203e2fac9","ThermostatID": "1021410","ViewType": 2,"DateTime": Date,"History": 0} %}
        {{ payload | to_json }}
    value_template: '{{ value_json.EnergyUsage[0].Usage[0].EnergyKWattHour | round(2) }}'
    unit_of_measurement: "kWh"
    device_class: energy
    scan_interval: 60
```

```json
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \ 
   "APIKEY": "f219aab4-9ac0-4343-8422-b72203e2fac9", \ 
   "ThermostatID": "XXXXXXX", \ 
   "ViewType": 2, \ 
   "DateTime": "2024-09-01", \  <-- DATE FROM TOMORROW
   "History": 0 \ 
 }' 'https://ocd5.azurewebsites.net/api/EnergyUsage/GetEnergyUsage?sessionid=DGmjV1CMN0mI8C6xuBBSQA'

{
  "EnergyUsage": [
    {
      "Usage": [
        {
          "EnergyKWattHour": 0 <-- Value [0] VALUE FROM TODAY 
        },
        {
          "EnergyKWattHour": 0.3515
        },
        {
          "EnergyKWattHour": 1.2272
        },
        {
          "EnergyKWattHour": 0.3268
        },
        {
          "EnergyKWattHour": 1.221
        },
        {
          "EnergyKWattHour": 1.1963
        },
        {
          "EnergyKWattHour": 0.0493
        }
      ]
    }
  ],
  "ErrorCode": 0
}
```
